---
name: paasta-portal                      # 서비스 배포이름(필수) bosh deployments 로 확인 가능한 이름

stemcells:
- alias: ((stemcell_alias))
  os: ((stemcell_os))
  version: "((stemcell_version))"
- alias: binary_storage_stemcells
  os: ((stemcell_os))
  version: 3468.51 



releases:
- name: "((releases_name))"                   # 서비스 릴리즈 이름(필수) bosh releases로 확인 가능
  version: "2.0"                                              # 서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

update:
  canaries: 1                                               # canary 인스턴스 수(필수)
  canary_watch_time: 5000-120000                            # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  update_watch_time: 5000-120000                            # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 1                                          # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  serial: false

instance_groups:
########## INFRA ##########
- name: mariadb
  azs:
  - z6
  instances: 1
  vm_type: "((vm_type_small))"
  stemcell: "((stemcell_alias))"
  persistent_disk_type: "((mariadb_disk_type))"
  networks:
  - name: ((internal_networks_name))
  templates:
  - name: mariadb
    release: "((releases_name))" 
  syslog_aggregator: null

- name: haproxy
  azs:
  - z6
  instances: 1
  vm_type: "((vm_type_tiny))"
  stemcell: "((stemcell_alias))"
  networks:
  - name: ((internal_networks_name))
  - name: ((external_networks_name))
    static_ips: ((haproxy_public_ip))
  templates:
  - name: haproxy
    release: "((releases_name))"
  syslog_aggregator: null
  properties:

- name: binary_storage
  azs:
  - z6
  instances: 1
  persistent_disk_type: "((binary_storage_disk_type))"
  vm_type: "((vm_type_small))"
  stemcell: binary_storage_stemcells
  networks:
  - name: ((internal_networks_name))
  templates:
  - name: binary_storage
    release: "((releases_name))"
  syslog_aggregator: null



######## WEB SERVICE ########

- name: paas-ta-portal-gateway
  azs:
  - z6
  instances: 1
  vm_type: "((vm_type_small))"
  stemcell: "((stemcell_alias))"
  networks:
  - name: ((internal_networks_name))
  templates:
  - name: paas-ta-portal-gateway
    release: "((releases_name))"
  syslog_aggregator: null
  properties:
    java_opts: "-Xmx450m -Xss1M -XX:MaxMetaspaceSize=93382K -XX:ReservedCodeCacheSize=240m -XX:+UseCompressedOops -Djdk.tls.ephemeralDHKeySize=2048 -Dfile.encoding=UTF-8 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Xverify:none -XX:ErrorFile=/var/vcap/sys/log/java_error_in_idea_%p.log -XX:HeapDumpPath=/var/vcap/sys/log/java_error_in_idea.hprof"

- name: paas-ta-portal-registration
  azs:
  - z6
  instances: 1
  vm_type: "((vm_type_small))"
  stemcell: "((stemcell_alias))"
  networks:
  - name: ((internal_networks_name))
  templates:
  - name: paas-ta-portal-registration
    release: "((releases_name))"
  syslog_aggregator: null
  properties:
    java_opts: "-Xmx450m -Xss1M -XX:MaxMetaspaceSize=93382K -XX:ReservedCodeCacheSize=240m -XX:+UseCompressedOops -Djdk.tls.ephemeralDHKeySize=2048 -Dfile.encoding=UTF-8 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Xverify:none -XX:ErrorFile=/var/vcap/sys/log/java_error_in_idea_%p.log -XX:HeapDumpPath=/var/vcap/sys/log/java_error_in_idea.hprof"
    server:
      port: 2221

- name: paas-ta-portal-api
  azs:
  - z6
  instances: 1
  vm_type: "((vm_type_medium))"
  stemcell: "((stemcell_alias))"
  networks:
  - name: ((internal_networks_name))
  templates:
  - name: paas-ta-portal-api
    release: "((releases_name))"
  syslog_aggregator: null
  properties:
    java_opts: "-Xmx900m -Xss1M -XX:MaxMetaspaceSize=93382K -XX:ReservedCodeCacheSize=240m -XX:+UseCompressedOops -Djdk.tls.ephemeralDHKeySize=2048 -Dfile.encoding=UTF-8 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Xverify:none -XX:ErrorFile=/var/vcap/sys/log/java_error_in_idea_%p.log -XX:HeapDumpPath=/var/vcap/sys/log/java_error_in_idea.hprof"
    cloudfoundry:
      cc:
        api:
          url: ((cf_api_url))
          uaaUrl: ((cf_uaa_url))
          sslSkipValidation: true
      user: # CloudFoundry Login information
        admin:
          username: admin
          password: "((cf_admin_password))"
        uaaClient:
          clientId: admin
          clientSecret: ((cf_uaa_admin_client_secret))
          adminClientId: admin
          adminClientSecret: ((cf_uaa_admin_client_secret))
          loginClientId: admin
          loginClientSecret: ((cf_uaa_admin_client_secret))
          skipSSLValidation: true
      authorization: cf-Authorization
    abacus:
      url: ((abacus_url))
    monitoring:
      api:
        url: ((monitoring_api_url))

- name: paas-ta-portal-common-api
  azs:
  - z6
  instances: 1
  vm_type: "((vm_type_small))"
  stemcell: "((stemcell_alias))"
  networks:
  - name: ((internal_networks_name))
  templates:
  - name: paas-ta-portal-common-api
    release: "((releases_name))"
  syslog_aggregator: null
  properties:
    java_opts: "-Xmx450m -Xss1M -XX:MaxMetaspaceSize=93382K -XX:ReservedCodeCacheSize=240m -XX:+UseCompressedOops -Djdk.tls.ephemeralDHKeySize=2048 -Dfile.encoding=UTF-8 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Xverify:none -XX:ErrorFile=/var/vcap/sys/log/java_error_in_idea_%p.log -XX:HeapDumpPath=/var/vcap/sys/log/java_error_in_idea.hprof"
    datasource:
      cc:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://((cf_db_ips)):((cf_db_port))/cloud_controller
        username: "((cc_db_id))"
        password: "((cc_db_password))"
      portal:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: "((mariadb_user_password))"
      uaa:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://((cf_db_ips)):((cf_db_port))/uaa
        username: "((uaa_db_id))"
        password: "((uaa_db_password))"
    mail:
      smtp:
        host: ((mail_smtp_host))
        port: ((mail_smtp_port))
        username: ((mail_smtp_username))
        password: "((mail_smtp_password))"
        useremail: ((mail_smtp_useremail))
        properties:
          auth: ((mail_smtp_properties_auth))
          starttls:
            enable: ((mail_smtp_properties_starttls_enable))
            required: ((mail_smtp_properties_starttls_required))
          maximumTotalQps: 90
          authUrl: ((paas_ta_web_user_url))
          charset: UTF-8
          subject: "((mail_smtp_properties_subject))"
          createUrl: authcreate
          expiredUrl: authreset
          inviteUrl: inviteorg

- name: paas-ta-portal-storage-api
  azs:
  - z6
  instances: 1
  vm_type: "((vm_type_small))"
  stemcell: "((stemcell_alias))"
  networks:
  - name: ((internal_networks_name))
  templates:
  - name: paas-ta-portal-storage-api
    release: "((releases_name))"
  syslog_aggregator: null
  properties:
    java_opts: "-Xmx450m -Xss1M -XX:MaxMetaspaceSize=93382K -XX:ReservedCodeCacheSize=240m -XX:+UseCompressedOops -Djdk.tls.ephemeralDHKeySize=2048 -Dfile.encoding=UTF-8 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Xverify:none -XX:ErrorFile=/var/vcap/sys/log/java_error_in_idea_%p.log -XX:HeapDumpPath=/var/vcap/sys/log/java_error_in_idea.hprof"
    objectStorage:
      swift:
        tenantName: ((binary_storage_tenantname))
        username: ((binary_storage_username))
        password: ((binary_storage_password))
        authUrl: http://((binary_storage_ips)):5000/v2.0/tokens
        authMethod: keystone
        preferredRegion: Public
        container: portal-container

- name : paas-ta-portal-log-api
  azs:
  - z6
  instances: 1
  vm_type: "((vm_type_small))"
  stemcell: "((stemcell_alias))"
  networks:
  - name: ((internal_networks_name))
  templates:
  - name: paas-ta-portal-log-api
    release: "((releases_name))" 
  syslog_aggregator: null
  properties:
    java_opts: "-Xmx450m -Xss1M -XX:MaxMetaspaceSize=93382K -XX:ReservedCodeCacheSize=240m -XX:+UseCompressedOops -Djdk.tls.ephemeralDHKeySize=2048 -Dfile.encoding=UTF-8 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Xverify:none -XX:ErrorFile=/var/vcap/sys/log/java_error_in_idea_%p.log -XX:HeapDumpPath=/var/vcap/sys/log/java_error_in_idea.hprof"
    cloudfoundry:
      cc:
        api:
          url: ((cf_api_url))
          uaaUrl: ((cf_uaa_url))
          sslSkipValidation: true
      user: # CloudFoundry Login information
        admin:
          username: admin
          password: "((cf_admin_password))"
        uaaClient:
          clientId: login
          clientSecret: login-secret
          adminClientId: admin
          adminClientSecret: "((cf_uaa_admin_client_secret))"
          loginClientId: login
          loginClientSecret: login-secret
          skipSSLValidation: true
      authorization: cf-Authorization

- name: paas-ta-portal-webadmin
  azs:
  - z6
  instances: 1
  vm_type: "((vm_type_small))"
  stemcell: "((stemcell_alias))"
  networks:
  - name: ((internal_networks_name))
  templates:
  - name: paas-ta-portal-webadmin
    release: "((releases_name))"
  syslog_aggregator: null
  properties:
    java_opts: "-Xmx450m -Xss1M -XX:MaxMetaspaceSize=93382K -XX:ReservedCodeCacheSize=240m -XX:+UseCompressedOops -Djdk.tls.ephemeralDHKeySize=2048 -Dfile.encoding=UTF-8 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Xverify:none -XX:ErrorFile=/var/vcap/sys/log/java_error_in_idea_%p.log -XX:HeapDumpPath=/var/vcap/sys/log/java_error_in_idea.hprof"

- name: paas-ta-portal-webuser
  azs:
  - z6
  instances: 1
  vm_type: "((vm_type_tiny))"
  stemcell: "((stemcell_alias))"
  networks:
  - name: ((internal_networks_name))
  templates:
  - name: paas-ta-portal-webuser
    release: "((releases_name))"
  syslog_aggregator: null
  properties:
    logPath: "/var/vcap/sys/log/paas-ta-portal-webuser"   # WEBUSER는 아파치를 사용함, APACHE 로그 위치
    webDir: "/var/vcap/packages/apache2/htdocs"           # WEBUSER는 아파치를 사용함, APACHE 웹 디렉토리 설정
    cf:
      uaa:
        url: ((cf_uaa_url))
        clientsecret: ((portal_client_secret))
        logouturl: ((cf_uaa_logouturl))
    monitoring: ((portal_webuser_monitoring))
    quantity: ((portal_webuser_quantity))
    automaticApproval: ((portal_webuser_automaticapproval))



properties:
  mariadb:                                                # MARIA DB SERVER 설정 정보
    port: ((mariadb_port))                                            # MARIA DB PORT 번호
    admin_user:
      password: '((mariadb_user_password))'                             # MARIA DB ROOT 계정 비밀번호
    host_names:
    - mariadb0
  binary_storage:                                         # BINARY STORAGE SERVER 설정 정보
    proxy_port: 10008                                     # 프록시 서버 Port(Object Storage >접속 Port)
    auth_port: 5000
    username:                                             # 최초 생성되는 유저이름(Object Storage 접속 유저이름)
    - ((binary_storage_username))
    password:                                             # 최초 생성되는 유저 비밀번호(Object Storage 접속 유저 비밀번호)
    - ((binary_storage_password))
    tenantname:                                           # 최초 생성되는 테넌트 이름(Object Storage 접속 테넌트 이름)
    - ((binary_storage_tenantname))
    email:                                                # 최소 생성되는 유저의 이메일
    - ((binary_storage_email))
    container:                                            # 최초 생성되는 컨테이너 이름
    - portal-container
    binary_desc:                                          # 최초 생성되는 컨테이너에 대한 설>명
    - "portal binary_storage"
